### PR TITLE
adds config dry run

### PR DESCRIPTION
**Pull request by fredshone**
enables a config dry run:

`elara run -d ~/Data/TE/elara_config.toml` or `elara run -dry_run ~/Data/TE/elara_config.toml`

which is of limited use given that `elara run` already effectivelly does a dry run (so i'm not proposing to add documentation). But this PR also includes some minor changes to give better feedback.

I also completely removed the requirement for "name" in the config, eg:

```
[scenario]
name = "default"
```

This was already removed from almost all the output files names so was redundant.

### CODE REVIEW

**Review by akay-arup — APPROVED** [review]
Nice one @fredshone -- much more helpful. 

Approved, but I'd propose sneakily just throwing in one line into the `Command Line Reference` section of the README. 

Would be even better if this caught the TOML error so you don't have to see the full traceback. But that's a `ValueError` rather than a custom exception, so seems a bit iffy to try that. 🤷‍♂️ 

We should consider expanding the scope for dry-runs to check for tool names against the registered workstations and try to provide a helpful steer. Current behaviour for misspelled/wrong tool names is just to fail to satisfy requirements.

Thinking about a warning like:

```
UserWarning:
No tool called link_vehicle_count...did you mean `link_vehicle_counts`?
```
Could use fuzzywuzzy etc.

**Comment by fredshone** [comment]
adds hopefully useful error message using fuzzy, eg:
```
ValueError: Failure to find at least one requirement, this may be an error with your config:
RequirementsWorkStation workstation cannot find requirement: 'passenger_log'.
	did you mean: 'vehicle_passenger_log' (EventHandlerWorkStation)
	did you mean: 'link_passenger_counts' (EventHandlerWorkStation)
	did you mean: 'route_passenger_counts' (EventHandlerWorkStation)
RequirementsWorkStation workstation cannot find requirement: 'vhicle_departure_log'.
	did you mean: 'vehicle_departure_log' (EventHandlerWorkStation)
```

**Review by akay-arup — CHANGES_REQUESTED** [review]
Rad. Quick work on a Thursday night. 

I hate to be precious about the docstring format -- but will be important if we want to later implement sphinx or similar autodocumenting solutions.

**Review by akay-arup — APPROVED** [review]
great. approved!

**Pull request merged**
